// flow-typed signature: 4c7bc1ba46523ffe6998917cb0992d26
// flow-typed version: <<STUB>>/async-validator_v^1.10.1/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'async-validator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'async-validator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'async-validator/es/index' {
  declare module.exports: any;
}

declare module 'async-validator/es/messages' {
  declare module.exports: any;
}

declare module 'async-validator/es/rule/enum' {
  declare module.exports: any;
}

declare module 'async-validator/es/rule/index' {
  declare module.exports: any;
}

declare module 'async-validator/es/rule/pattern' {
  declare module.exports: any;
}

declare module 'async-validator/es/rule/range' {
  declare module.exports: any;
}

declare module 'async-validator/es/rule/required' {
  declare module.exports: any;
}

declare module 'async-validator/es/rule/type' {
  declare module.exports: any;
}

declare module 'async-validator/es/rule/whitespace' {
  declare module.exports: any;
}

declare module 'async-validator/es/util' {
  declare module.exports: any;
}

declare module 'async-validator/es/validator/array' {
  declare module.exports: any;
}

declare module 'async-validator/es/validator/boolean' {
  declare module.exports: any;
}

declare module 'async-validator/es/validator/date' {
  declare module.exports: any;
}

declare module 'async-validator/es/validator/enum' {
  declare module.exports: any;
}

declare module 'async-validator/es/validator/float' {
  declare module.exports: any;
}

declare module 'async-validator/es/validator/index' {
  declare module.exports: any;
}

declare module 'async-validator/es/validator/integer' {
  declare module.exports: any;
}

declare module 'async-validator/es/validator/method' {
  declare module.exports: any;
}

declare module 'async-validator/es/validator/number' {
  declare module.exports: any;
}

declare module 'async-validator/es/validator/object' {
  declare module.exports: any;
}

declare module 'async-validator/es/validator/pattern' {
  declare module.exports: any;
}

declare module 'async-validator/es/validator/regexp' {
  declare module.exports: any;
}

declare module 'async-validator/es/validator/required' {
  declare module.exports: any;
}

declare module 'async-validator/es/validator/string' {
  declare module.exports: any;
}

declare module 'async-validator/es/validator/type' {
  declare module.exports: any;
}

declare module 'async-validator/lib/index' {
  declare module.exports: any;
}

declare module 'async-validator/lib/messages' {
  declare module.exports: any;
}

declare module 'async-validator/lib/rule/enum' {
  declare module.exports: any;
}

declare module 'async-validator/lib/rule/index' {
  declare module.exports: any;
}

declare module 'async-validator/lib/rule/pattern' {
  declare module.exports: any;
}

declare module 'async-validator/lib/rule/range' {
  declare module.exports: any;
}

declare module 'async-validator/lib/rule/required' {
  declare module.exports: any;
}

declare module 'async-validator/lib/rule/type' {
  declare module.exports: any;
}

declare module 'async-validator/lib/rule/whitespace' {
  declare module.exports: any;
}

declare module 'async-validator/lib/util' {
  declare module.exports: any;
}

declare module 'async-validator/lib/validator/array' {
  declare module.exports: any;
}

declare module 'async-validator/lib/validator/boolean' {
  declare module.exports: any;
}

declare module 'async-validator/lib/validator/date' {
  declare module.exports: any;
}

declare module 'async-validator/lib/validator/enum' {
  declare module.exports: any;
}

declare module 'async-validator/lib/validator/float' {
  declare module.exports: any;
}

declare module 'async-validator/lib/validator/index' {
  declare module.exports: any;
}

declare module 'async-validator/lib/validator/integer' {
  declare module.exports: any;
}

declare module 'async-validator/lib/validator/method' {
  declare module.exports: any;
}

declare module 'async-validator/lib/validator/number' {
  declare module.exports: any;
}

declare module 'async-validator/lib/validator/object' {
  declare module.exports: any;
}

declare module 'async-validator/lib/validator/pattern' {
  declare module.exports: any;
}

declare module 'async-validator/lib/validator/regexp' {
  declare module.exports: any;
}

declare module 'async-validator/lib/validator/required' {
  declare module.exports: any;
}

declare module 'async-validator/lib/validator/string' {
  declare module.exports: any;
}

declare module 'async-validator/lib/validator/type' {
  declare module.exports: any;
}

// Filename aliases
declare module 'async-validator/es/index.js' {
  declare module.exports: $Exports<'async-validator/es/index'>;
}
declare module 'async-validator/es/messages.js' {
  declare module.exports: $Exports<'async-validator/es/messages'>;
}
declare module 'async-validator/es/rule/enum.js' {
  declare module.exports: $Exports<'async-validator/es/rule/enum'>;
}
declare module 'async-validator/es/rule/index.js' {
  declare module.exports: $Exports<'async-validator/es/rule/index'>;
}
declare module 'async-validator/es/rule/pattern.js' {
  declare module.exports: $Exports<'async-validator/es/rule/pattern'>;
}
declare module 'async-validator/es/rule/range.js' {
  declare module.exports: $Exports<'async-validator/es/rule/range'>;
}
declare module 'async-validator/es/rule/required.js' {
  declare module.exports: $Exports<'async-validator/es/rule/required'>;
}
declare module 'async-validator/es/rule/type.js' {
  declare module.exports: $Exports<'async-validator/es/rule/type'>;
}
declare module 'async-validator/es/rule/whitespace.js' {
  declare module.exports: $Exports<'async-validator/es/rule/whitespace'>;
}
declare module 'async-validator/es/util.js' {
  declare module.exports: $Exports<'async-validator/es/util'>;
}
declare module 'async-validator/es/validator/array.js' {
  declare module.exports: $Exports<'async-validator/es/validator/array'>;
}
declare module 'async-validator/es/validator/boolean.js' {
  declare module.exports: $Exports<'async-validator/es/validator/boolean'>;
}
declare module 'async-validator/es/validator/date.js' {
  declare module.exports: $Exports<'async-validator/es/validator/date'>;
}
declare module 'async-validator/es/validator/enum.js' {
  declare module.exports: $Exports<'async-validator/es/validator/enum'>;
}
declare module 'async-validator/es/validator/float.js' {
  declare module.exports: $Exports<'async-validator/es/validator/float'>;
}
declare module 'async-validator/es/validator/index.js' {
  declare module.exports: $Exports<'async-validator/es/validator/index'>;
}
declare module 'async-validator/es/validator/integer.js' {
  declare module.exports: $Exports<'async-validator/es/validator/integer'>;
}
declare module 'async-validator/es/validator/method.js' {
  declare module.exports: $Exports<'async-validator/es/validator/method'>;
}
declare module 'async-validator/es/validator/number.js' {
  declare module.exports: $Exports<'async-validator/es/validator/number'>;
}
declare module 'async-validator/es/validator/object.js' {
  declare module.exports: $Exports<'async-validator/es/validator/object'>;
}
declare module 'async-validator/es/validator/pattern.js' {
  declare module.exports: $Exports<'async-validator/es/validator/pattern'>;
}
declare module 'async-validator/es/validator/regexp.js' {
  declare module.exports: $Exports<'async-validator/es/validator/regexp'>;
}
declare module 'async-validator/es/validator/required.js' {
  declare module.exports: $Exports<'async-validator/es/validator/required'>;
}
declare module 'async-validator/es/validator/string.js' {
  declare module.exports: $Exports<'async-validator/es/validator/string'>;
}
declare module 'async-validator/es/validator/type.js' {
  declare module.exports: $Exports<'async-validator/es/validator/type'>;
}
declare module 'async-validator/lib/index.js' {
  declare module.exports: $Exports<'async-validator/lib/index'>;
}
declare module 'async-validator/lib/messages.js' {
  declare module.exports: $Exports<'async-validator/lib/messages'>;
}
declare module 'async-validator/lib/rule/enum.js' {
  declare module.exports: $Exports<'async-validator/lib/rule/enum'>;
}
declare module 'async-validator/lib/rule/index.js' {
  declare module.exports: $Exports<'async-validator/lib/rule/index'>;
}
declare module 'async-validator/lib/rule/pattern.js' {
  declare module.exports: $Exports<'async-validator/lib/rule/pattern'>;
}
declare module 'async-validator/lib/rule/range.js' {
  declare module.exports: $Exports<'async-validator/lib/rule/range'>;
}
declare module 'async-validator/lib/rule/required.js' {
  declare module.exports: $Exports<'async-validator/lib/rule/required'>;
}
declare module 'async-validator/lib/rule/type.js' {
  declare module.exports: $Exports<'async-validator/lib/rule/type'>;
}
declare module 'async-validator/lib/rule/whitespace.js' {
  declare module.exports: $Exports<'async-validator/lib/rule/whitespace'>;
}
declare module 'async-validator/lib/util.js' {
  declare module.exports: $Exports<'async-validator/lib/util'>;
}
declare module 'async-validator/lib/validator/array.js' {
  declare module.exports: $Exports<'async-validator/lib/validator/array'>;
}
declare module 'async-validator/lib/validator/boolean.js' {
  declare module.exports: $Exports<'async-validator/lib/validator/boolean'>;
}
declare module 'async-validator/lib/validator/date.js' {
  declare module.exports: $Exports<'async-validator/lib/validator/date'>;
}
declare module 'async-validator/lib/validator/enum.js' {
  declare module.exports: $Exports<'async-validator/lib/validator/enum'>;
}
declare module 'async-validator/lib/validator/float.js' {
  declare module.exports: $Exports<'async-validator/lib/validator/float'>;
}
declare module 'async-validator/lib/validator/index.js' {
  declare module.exports: $Exports<'async-validator/lib/validator/index'>;
}
declare module 'async-validator/lib/validator/integer.js' {
  declare module.exports: $Exports<'async-validator/lib/validator/integer'>;
}
declare module 'async-validator/lib/validator/method.js' {
  declare module.exports: $Exports<'async-validator/lib/validator/method'>;
}
declare module 'async-validator/lib/validator/number.js' {
  declare module.exports: $Exports<'async-validator/lib/validator/number'>;
}
declare module 'async-validator/lib/validator/object.js' {
  declare module.exports: $Exports<'async-validator/lib/validator/object'>;
}
declare module 'async-validator/lib/validator/pattern.js' {
  declare module.exports: $Exports<'async-validator/lib/validator/pattern'>;
}
declare module 'async-validator/lib/validator/regexp.js' {
  declare module.exports: $Exports<'async-validator/lib/validator/regexp'>;
}
declare module 'async-validator/lib/validator/required.js' {
  declare module.exports: $Exports<'async-validator/lib/validator/required'>;
}
declare module 'async-validator/lib/validator/string.js' {
  declare module.exports: $Exports<'async-validator/lib/validator/string'>;
}
declare module 'async-validator/lib/validator/type.js' {
  declare module.exports: $Exports<'async-validator/lib/validator/type'>;
}
