// flow-typed signature: a821ecd40b615179e7d1be56a1518bac
// flow-typed version: <<STUB>>/markdown-it-container_v^2.0.0/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'markdown-it-container'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'markdown-it-container' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'markdown-it-container/dist/markdown-it-container' {
  declare module.exports: any;
}

declare module 'markdown-it-container/dist/markdown-it-container.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'markdown-it-container/dist/markdown-it-container.js' {
  declare module.exports: $Exports<'markdown-it-container/dist/markdown-it-container'>;
}
declare module 'markdown-it-container/dist/markdown-it-container.min.js' {
  declare module.exports: $Exports<'markdown-it-container/dist/markdown-it-container.min'>;
}
declare module 'markdown-it-container/index' {
  declare module.exports: $Exports<'markdown-it-container'>;
}
declare module 'markdown-it-container/index.js' {
  declare module.exports: $Exports<'markdown-it-container'>;
}
