// flow-typed signature: 0de1d0b1374fa3ac011071536f76521d
// flow-typed version: <<STUB>>/vue-router_v^3.0.1/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-router' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-router/dist/vue-router.common' {
  declare module.exports: any;
}

declare module 'vue-router/dist/vue-router.esm.browser' {
  declare module.exports: any;
}

declare module 'vue-router/dist/vue-router.esm.browser.min' {
  declare module.exports: any;
}

declare module 'vue-router/dist/vue-router.esm' {
  declare module.exports: any;
}

declare module 'vue-router/dist/vue-router' {
  declare module.exports: any;
}

declare module 'vue-router/dist/vue-router.min' {
  declare module.exports: any;
}

declare module 'vue-router/src/create-matcher' {
  declare module.exports: any;
}

declare module 'vue-router/src/create-route-map' {
  declare module.exports: any;
}

declare module 'vue-router/src/index' {
  declare module.exports: any;
}

declare module 'vue-router/src/install' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-router/dist/vue-router.common.js' {
  declare module.exports: $Exports<'vue-router/dist/vue-router.common'>;
}
declare module 'vue-router/dist/vue-router.esm.browser.js' {
  declare module.exports: $Exports<'vue-router/dist/vue-router.esm.browser'>;
}
declare module 'vue-router/dist/vue-router.esm.browser.min.js' {
  declare module.exports: $Exports<'vue-router/dist/vue-router.esm.browser.min'>;
}
declare module 'vue-router/dist/vue-router.esm.js' {
  declare module.exports: $Exports<'vue-router/dist/vue-router.esm'>;
}
declare module 'vue-router/dist/vue-router.js' {
  declare module.exports: $Exports<'vue-router/dist/vue-router'>;
}
declare module 'vue-router/dist/vue-router.min.js' {
  declare module.exports: $Exports<'vue-router/dist/vue-router.min'>;
}
declare module 'vue-router/src/create-matcher.js' {
  declare module.exports: $Exports<'vue-router/src/create-matcher'>;
}
declare module 'vue-router/src/create-route-map.js' {
  declare module.exports: $Exports<'vue-router/src/create-route-map'>;
}
declare module 'vue-router/src/index.js' {
  declare module.exports: $Exports<'vue-router/src/index'>;
}
declare module 'vue-router/src/install.js' {
  declare module.exports: $Exports<'vue-router/src/install'>;
}
