// flow-typed signature: 5faa7e8489c7087379c4ce306a83f9d7
// flow-typed version: <<STUB>>/vue-markdown_v^2.2.4/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-markdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-markdown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-markdown/dist/vue-markdown.common' {
  declare module.exports: any;
}

declare module 'vue-markdown/dist/vue-markdown' {
  declare module.exports: any;
}

declare module 'vue-markdown/src/build' {
  declare module.exports: any;
}

declare module 'vue-markdown/src/VueMarkdown' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-markdown/dist/vue-markdown.common.js' {
  declare module.exports: $Exports<'vue-markdown/dist/vue-markdown.common'>;
}
declare module 'vue-markdown/dist/vue-markdown.js' {
  declare module.exports: $Exports<'vue-markdown/dist/vue-markdown'>;
}
declare module 'vue-markdown/src/build.js' {
  declare module.exports: $Exports<'vue-markdown/src/build'>;
}
declare module 'vue-markdown/src/VueMarkdown.js' {
  declare module.exports: $Exports<'vue-markdown/src/VueMarkdown'>;
}
