// flow-typed signature: 782a51238ad1447de58db99059178287
// flow-typed version: <<STUB>>/vue-markdown-loader_v^2.4.1/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-markdown-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-markdown-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-markdown-loader/example/src/entry' {
  declare module.exports: any;
}

declare module 'vue-markdown-loader/example/webpack.config' {
  declare module.exports: any;
}

declare module 'vue-markdown-loader/lib/core' {
  declare module.exports: any;
}

declare module 'vue-markdown-loader/lib/markdown-compiler' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-markdown-loader/example/src/entry.js' {
  declare module.exports: $Exports<'vue-markdown-loader/example/src/entry'>;
}
declare module 'vue-markdown-loader/example/webpack.config.js' {
  declare module.exports: $Exports<'vue-markdown-loader/example/webpack.config'>;
}
declare module 'vue-markdown-loader/index' {
  declare module.exports: $Exports<'vue-markdown-loader'>;
}
declare module 'vue-markdown-loader/index.js' {
  declare module.exports: $Exports<'vue-markdown-loader'>;
}
declare module 'vue-markdown-loader/lib/core.js' {
  declare module.exports: $Exports<'vue-markdown-loader/lib/core'>;
}
declare module 'vue-markdown-loader/lib/markdown-compiler.js' {
  declare module.exports: $Exports<'vue-markdown-loader/lib/markdown-compiler'>;
}
