// flow-typed signature: fab2b3abb0fc51187227303159b01d14
// flow-typed version: <<STUB>>/vue-awesome-swiper_v^3.1.3/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-awesome-swiper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-awesome-swiper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-awesome-swiper/dist/ssr' {
  declare module.exports: any;
}

declare module 'vue-awesome-swiper/dist/vue-awesome-swiper' {
  declare module.exports: any;
}

declare module 'vue-awesome-swiper/src/index' {
  declare module.exports: any;
}

declare module 'vue-awesome-swiper/src/ssr' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-awesome-swiper/dist/ssr.js' {
  declare module.exports: $Exports<'vue-awesome-swiper/dist/ssr'>;
}
declare module 'vue-awesome-swiper/dist/vue-awesome-swiper.js' {
  declare module.exports: $Exports<'vue-awesome-swiper/dist/vue-awesome-swiper'>;
}
declare module 'vue-awesome-swiper/src/index.js' {
  declare module.exports: $Exports<'vue-awesome-swiper/src/index'>;
}
declare module 'vue-awesome-swiper/src/ssr.js' {
  declare module.exports: $Exports<'vue-awesome-swiper/src/ssr'>;
}
