// flow-typed signature: 340dee73c69649c9929af06df58df917
// flow-typed version: <<STUB>>/vue-radial-progress_v^0.2.10/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-radial-progress'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-radial-progress' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-radial-progress/dist/vue-radial-progress.min' {
  declare module.exports: any;
}

declare module 'vue-radial-progress/src/main' {
  declare module.exports: any;
}

declare module 'vue-radial-progress/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-radial-progress/dist/vue-radial-progress.min.js' {
  declare module.exports: $Exports<'vue-radial-progress/dist/vue-radial-progress.min'>;
}
declare module 'vue-radial-progress/src/main.js' {
  declare module.exports: $Exports<'vue-radial-progress/src/main'>;
}
declare module 'vue-radial-progress/webpack.config.js' {
  declare module.exports: $Exports<'vue-radial-progress/webpack.config'>;
}
