// flow-typed signature: 4ba11b880345fcb5cc620ad631846316
// flow-typed version: <<STUB>>/@vue/server-test-utils_v^1.0.0-beta.28/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@vue/server-test-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@vue/server-test-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@vue/server-test-utils/dist/vue-server-test-utils' {
  declare module.exports: any;
}

// Filename aliases
declare module '@vue/server-test-utils/dist/vue-server-test-utils.js' {
  declare module.exports: $Exports<'@vue/server-test-utils/dist/vue-server-test-utils'>;
}
