const menu = 'MENU';
const button = 'BUTTON';
const SERVER_APP = 'APPLICATION';
const SERVER_USER = 'USER-MANAGER';
const SERVER_PROJECT = 'PROJECT-MANAGER';
const SERVER_MODEL = 'MODEL-MANAGER';
const SERVER_IMAGE = 'IMAGE-MANAGER';
const SERVER_FILE = 'FILE-MANAGER';
const SERVER_DATA = 'DATA-MANAGER';
const SERVER_SKYFLOW = 'SKYFLOW-MANAGER';
const SERVER_RESOURCE = 'RESOURCE-MANAGER';
const SERVER_SYSTEM = 'SYSTEM-MANAGER';

export default {
    // 菜单访问权限
    DASHBOARD_MENU_ACCESS: `${SERVER_APP}:DASHBOARD_MENU:ACCESS:""`,
    PROJECT_MENU_ACCESS: `${SERVER_APP}:PROJECT_MANAGER_MENU:ACCESS:""`,
    DATA_MENU_ACCESS: `${SERVER_APP}:DATA_MANAGER_MENU:ACCESS:""`,
    SKYFLOW_MENU_ACCESS: `${SERVER_APP}:SKYFLOW_MANAGER_MENU:ACCESS:""`,
    FILE_MENU_ACCESS: `${SERVER_APP}:FILE_MANAGER_MENU:ACCESS:""`,
    IMAGE_MENU_ACCESS: `${SERVER_APP}:IMAGE_MANAGER_MENU:ACCESS:""`,
    MODEL_MENU_ACCESS: `${SERVER_APP}:MODEL_MANAGER_MENU:ACCESS:""`,
    MANAGE_PLATFORM_ACCESS: `${SERVER_APP}:MANAEGR_PLATFORM_MENU:ACCESS:""`,
    USER_MENU_ACCESS: `${SERVER_APP}:USER_MANAGER_MENU:ACCESS:""`,
    PERMISSION_MENU_ACCESS: `${SERVER_APP}:PERMISSION_MANAGER_MENU:ACCESS:""`,
    RESOURCE_MENU_ACCESS: `${SERVER_APP}:RESOURCE_MANAGER_MENU:ACCESS:""`,
    SYSTEM_MENU_ACCESS: `${SERVER_APP}:SYSTEM_MANAGER_MENU:ACCESS:""`,

    // 按钮访问权限
    RESOURCE_TEMPLATE_READ: `${SERVER_RESOURCE}:TEMPLATE:READ:""`,
    RESOURCE_TEMPLATE_WRITE: `${SERVER_RESOURCE}:TEMPLATE:WRITE:""`,
    RESOURCE_CONFIG_READ: `${SERVER_RESOURCE}:CONFIG:READ:""`,
    RESOURCE_CONFIG_WRITE: `${SERVER_RESOURCE}:CONFIG:WRITE:""`,
}
